name: SSH over Ngrok

on:
  workflow_dispatch:   # Manuel tetiklemek için
  push:                # Push ile de çalıştırmak istersen

jobs:
  ssh-ngrok:
    runs-on: ubuntu-latest

    steps:
    - name: Update apt
      run: sudo apt-get update -qq

    - name: Install SSH server
      run: |
        sudo apt-get install -y openssh-server
        echo "root:123456" | sudo chpasswd
        sudo mkdir -p /var/run/sshd
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh start

    - name: Install Ngrok
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update -qq
        sudo apt install -y ngrok jq

    - name: Run Ngrok Tunnel
      run: |
        # Buraya token'ını direkt yazıyoruz
        NGROK_TOKEN="322kxh8nkxOhVpEKTEW5DLLHiRL_5zWcjmqbxpaghY2xb9G6i"
        nohup ngrok tcp 22 --authtoken $NGROK_TOKEN > ngrok.log 2>&1 &
        sleep 10
        echo "📜 Ngrok Log:"
        cat ngrok.log
        echo "🔗 Tünel URL’i:"
        curl http://localhost:4040/api/tunnels

    - name: Print SSH Command
      run: |
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        HOST_PORT=$(echo $NGROK_URL | sed 's/tcp:\/\///' | sed 's/:/ -p /')
        echo "🔑 SSH Bağlantısı Hazır:"
        echo "ssh root@$HOST_PORT"
        echo "Şifre: 123456"
