name: SSH over Ngrok

on:
  workflow_dispatch:   # Manuel tetiklemek için
  push:                # Push ile de çalıştırmak istersen

jobs:
  ssh-ngrok:
    runs-on: self-hosted   # Self-hosted runner olmalı, aksi halde job VM biterse tünel kapanır

    steps:
    - name: Update apt
      run: sudo apt-get update -qq

    - name: Install SSH server
      run: |
        sudo apt-get install -y openssh-server
        echo "root:123456" | sudo chpasswd
        sudo mkdir -p /var/run/sshd
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo service ssh start

    - name: Install Ngrok
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update -qq
        sudo apt install -y ngrok jq

    - name: Run Ngrok Tunnel and Keep Alive
      run: |
        NGROK_TOKEN="2yBP8xeJ21kecv1rmpPXvO9YA0V_4vCVix96ZGJwravydUxMc"
        # Sonsuz döngü ile ngrok'u sürekli çalıştır
        while true; do
          echo "🔄 Ngrok tüneli başlatılıyor..."
          nohup ngrok tcp 22 --authtoken $NGROK_TOKEN > ngrok.log 2>&1 &
          sleep 10
          echo "📜 Ngrok Log:"
          cat ngrok.log
          echo "🔗 Tünel URL’i:"
          curl http://localhost:4040/api/tunnels
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          HOST_PORT=$(echo $NGROK_URL | sed 's/tcp:\/\///' | sed 's/:/ -p /')
          echo "🔑 SSH Bağlantısı Hazır:"
          echo "ssh root@$HOST_PORT"
          echo "Şifre: 123456"
          sleep 300  # 5 dakikada bir tekrar kontrol ve yeniden başlatma
        done
